name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Production build of a project
      run: |
        npm install
        npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          docs
        retention-days: 3
      env:
        CI: true
